name: 'OpenAI ChatGPT based PR Reviewer & Summarizer'
description: 'OpenAI ChatGPT based PR Reviewer and Summarizer'
branding:
  icon: 'aperture'
  color: 'orange'
author: 'Alex D.'
inputs:
  debug:
    required: false
    description: 'Enable debug mode'
    default: 'false'
  path_filters:
    required: false
    description: |
      The path filters, e.g., "src/**.py", "!dist/**", each line will be considered as one pattern.
      See also

      - https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
      - https://github.com/isaacs/minimatch
    default: |
      !.changeset/**
      !.github/**
      !dist/**
      !**/*.md
      !**/*.pb.go
      !**/*.lock
      !**/*.yaml
      !**/*.yml
      !**/*.cfg
      !**/*.toml
      !**/*.ini
      !**/*.mod
      !**/*.sum
      !**/*.work
      !**/*.json
      !**/*.mmd
      !**/*.svg
      !**/*.png
      !**/*.dot
      !**/*.md5sum
      !**/*.wasm
      !**/gen/**
      !**/_gen/**
      !**/generated/**
      !**/vendor/**
  disable_review:
    required: false
    description: 'Only provide the summary and skip the code review.'
    default: 'false'
  disable_release_notes:
    required: false
    description: 'Disable release notes'
    default: 'false'
  openai_model:
    required: false
    description:
      'Model to use for simple tasks like summarizing diff on a file.'
    default: 'gpt-3.5-turbo'
  openai_model_temperature:
    required: false
    description: 'Temperature for GPT model'
    default: 0.2
  openai_retries:
    required: false
    description:
      'How many times to retry OpenAI API in case of timeouts or errors?'
    default: '5'
  system_message:
    required: false
    description: 'System message to be sent to OpenAI'
    default: |
      You are `@openai` (aka `github-actions[bot]`), a language model 
      trained by OpenAI. Your purpose is to act as a highly experienced 
      software engineer and provide a thorough review of the code hunks
      and suggest code snippets to improve key areas such as:
        - Logic
        - Security
        - Performance
        - Data races
        - Consistency
        - Error handling
        - Maintainability
        - Modularity
        - Complexity
        - Optimization

      Refrain from commenting on minor code style issues, missing 
      comments/documentation, or giving compliments, unless explicitly 
      requested. Concentrate on identifying and resolving significant 
      concerns to improve overall code quality while deliberately 
      disregarding minor issues.

      Note: As your knowledge may be outdated, trust the user code when newer
      APIs and methods are seemingly being used.
    user_message:
      required: true
      description: 'User message to be sent to OpenAI. Template supports variables ${fileName} and ${fileDiff}'
      default: |
        Below you'll find a diff of a file called ${fileName} which you need to do a code review and comment.

        each comment should be a json object with line, comment, suggestion and explanation fields.;
        suggestion field is optional, it should contain suggested code fixes for commented line if possible;
        explanation field is optional, it should contain information why do you think it's a wrong code or error;
    
        Final result should be like
        
        {
          file: ,
          comments: [
            { line: , comment: , suggestion:, explanation: }
          ]
        }
        
        Return response in JSON format
        
        where
        "line" - number of line in the file
        "comment" - your comment for it
        "suggestion" - how the line can be fixed
        
        How to parse file diff:
        For each line at the start you can find line number, use it in "line" field
        
        If file diff line starts with "-" sign, this line was deleted
        If file diff line starts with "+" sign, this line was added
        
        File diff:
        \\n --- \\n ${fileDiff} \\n --- \\n
runs:
  using: 'node16'
  main: 'dist/index.js'
